import { Footer } from "@/Components/Footer/Footer";
import { Header } from "@/Components/Header";
import { Provider } from "@/Providers/providers";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-purple-200">
        <Provider>
          <Header/>
          <div className="h-screen w-screen">
          {children}
          </div>
          <Footer/>
        </Provider>
      </body>
    </html>
  );
}
